[widgets.cloudwatch]
x = '0'
y = 'h / 2'
w = 'w / 2'
h = 'h / 2'
type = 'CloudWatchMetricImage'
invert = true
aws_profile = 'dashboard'
aws_region = 'us-east-1'
widget = '{"metrics": [[ "AWS/CloudFront", "Requests", "Region", "Global", "DistributionId", "YOUR_DISTRIBUTION_ID" ]],"view": "timeSeries","stacked": false,"stat": "Sum","period": 900, "width": w, "height": h,"start": "-PT72H", "end": "P0D", "timezone": "-0400"}'

[widgets.clock]
x = '0'
y = '0'
w = 'w / 2'
h = 'h / 2'
type = 'Clock'
clock_format = '%I:%M %p'
date_format = '%A, %B %d, %Y'
bg_color = '#000000'
fg_color = '#2196F3'
timezone = 'America/New_York'

[widgets.goes_world]
x = 'w / 2 '
y = 'h / 2'
w = 'w / 2'
h = 'h / 2'
type = 'SatelliteMap'
map_color = '#555555'
satellite_color = '#00FF00'
track_color = '#00AA00'
tle_url = 'https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle'
satellite_filter = 'ISS (ZARYA)'


[widgets.goes]
x = 'w / 2 + (w / 2 - h / 2) / 2'
y = '0'
w = 'h / 2'
h = 'h / 2'
type = 'Image'
path = 'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg'