[widgets.clock]
x = '0'
y = '0'
w = 'w / 2'
h = 'h / 2'
type = 'Clock'
clock_format = '%I:%M %p'
date_format = '%A, %B %d, %Y'
bg_color = '#000000'
fg_color = '#2196F3'
timezone = 'America/New_York'

[widgets.satellite_map]
swap_group = 'top_right'
x = '0'
y = 'h / 2'
w = 'w / 2'
h = 'h / 2'
type = 'SatelliteMap'
map_color = '#555555'
satellite_color = '#00FF00'
track_color = '#00AA00'
tle_url = 'https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle'
satellite_filter = 'ISS (ZARYA)'

[widgets.people_in_space]
swap_group = 'top_right'
x = 'w / 2 '
y = 'h / 2'
w = 'w / 2'
h = 'h / 2'
type = 'Metric'
url = 'http://api.open-notify.org/astros.json'
json_path = 'number'
label = 'People in Space'

[widgets.goes]
x = 'w / 2 + (w / 2 - h / 2) / 2'
y = '0'
w = 'h / 2'
h = 'h / 2'
type = 'Image'
path = 'https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg'